...
#Enhance your program to handle cases where two or all of the numbers are equal.
#The program should display appropriate messages like
#"Two numbers are equal and the largest" or "All numbers are equal".
...